# Generated by Django 5.2.5 on 2026-01-05 13:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobSeekerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('fresher', 'Fresher (0-2 years)'), ('experienced', 'Experienced Professional (2+ years)'), ('part_time', 'Part-time Worker'), ('freelancer', 'Freelancer')], default='fresher', max_length=20)),
                ('highest_education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('current_role', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('preferred_job_types', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_locations', models.TextField(blank=True, null=True)),
                ('salary_expectation', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='job_seeker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
