# Generated by Django 5.2.5 on 2026-01-08 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobSeekerProfile',
        ),
    ]
