# Generated by Django 5.2.5 on 2025-12-13 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('contact_person', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('industry', models.CharField(choices=[('it', 'Information Technology'), ('healthcare', 'Healthcare'), ('finance', 'Finance & Banking'), ('education', 'Education'), ('retail', 'Retail'), ('manufacturing', 'Manufacturing'), ('real_estate', 'Real Estate'), ('hospitality', 'Hospitality & Tourism'), ('legal', 'Legal Services'), ('engineering', 'Engineering'), ('design', 'Design & Creative'), ('marketing', 'Marketing & Advertising'), ('consulting', 'Consulting'), ('non_profit', 'Non-Profit'), ('other', 'Other')], max_length=50)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='company_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
