# Generated by Django 6.0.2 on 2026-02-12 14:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_jobcategory_options_alter_job_job_type'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='JobAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('search_params', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('search_params', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('headline', models.CharField(blank=True, max_length=200, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('user_type', models.CharField(choices=[('student', 'Student'), ('fresher', 'Fresher (0-2 years)'), ('experienced', 'Experienced Professional (2+ years)'), ('part_time', 'Part-time Worker'), ('freelancer', 'Freelancer')], default='fresher', max_length=20)),
                ('highest_education', models.CharField(blank=True, choices=[('high_school', 'High School'), ('diploma', 'Diploma'), ('bachelors', "Bachelor's Degree"), ('masters', "Master's Degree"), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True)),
                ('field_of_study', models.CharField(blank=True, max_length=200, null=True)),
                ('institution', models.CharField(blank=True, max_length=200, null=True)),
                ('graduation_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2031)])),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('current_role', models.CharField(blank=True, max_length=200, null=True)),
                ('current_company', models.CharField(blank=True, max_length=200, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('preferred_job_types', models.CharField(blank=True, max_length=200, null=True)),
                ('preferred_locations', models.TextField(blank=True, null=True)),
                ('salary_expectation', models.PositiveIntegerField(blank=True, help_text='Expected annual salary in whole rupees (e.g., 500000 for ₹5 Lakhs)', null=True)),
                ('portfolio_link', models.URLField(blank=True, null=True)),
                ('github_profile', models.URLField(blank=True, null=True)),
                ('linkedin_profile', models.URLField(blank=True, null=True)),
                ('availability_status', models.CharField(blank=True, choices=[('immediate', 'Immediately Available'), ('2_weeks', 'Available in 2 Weeks'), ('1_month', 'Available in 1 Month'), ('notice_period', 'Serving Notice Period'), ('not_available', 'Not Available')], default='immediate', max_length=20)),
                ('notice_period_days', models.IntegerField(blank=True, default=0)),
                ('expected_joining_date', models.DateField(blank=True, null=True)),
                ('work_preference', models.CharField(blank=True, choices=[('office', 'Office Only'), ('hybrid', 'Hybrid'), ('remote', 'Remote Only'), ('flexible', 'Flexible')], default='flexible', max_length=20)),
                ('willing_to_relocate', models.BooleanField(default=True)),
                ('willing_to_travel', models.BooleanField(default=False)),
                ('travel_percentage', models.IntegerField(blank=True, default=0)),
                ('is_active_seeker', models.BooleanField(default=True)),
                ('job_search_intensity', models.CharField(blank=True, choices=[('casual', 'Casual Search'), ('active', 'Active Search'), ('urgent', 'Urgent - Need Job ASAP')], default='active', max_length=20)),
                ('certifications', models.TextField(blank=True, null=True)),
                ('awards', models.TextField(blank=True, null=True)),
                ('preferred_company_size', models.CharField(blank=True, choices=[('startup', 'Startup (1-50 employees)'), ('small', 'Small (51-200 employees)'), ('medium', 'Medium (201-1000 employees)'), ('large', 'Large (1000+ employees)'), ('any', 'Any Size')], default='any', max_length=20)),
                ('ai_match_preferences', models.JSONField(blank=True, default=dict)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_applications', models.PositiveIntegerField(default=0)),
                ('applications_shortlisted', models.PositiveIntegerField(default=0)),
                ('applications_selected', models.PositiveIntegerField(default=0)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Seeker Profile',
                'verbose_name_plural': 'Job Seeker Profiles',
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-saved_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
