# Generated by Django 6.0.2 on 2026-02-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_application_review_notes_application_reviewed_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='application',
            name='jobs_applic_status_f83260_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='jobs_applic_job_id_a25382_idx',
        ),
        migrations.RemoveIndex(
            model_name='application',
            name='jobs_applic_candida_ced311_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='jobs_messag_recipie_129808_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='jobs_messag_sender__2bf833_idx',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='reschedule_reason',
        ),
        migrations.RemoveField(
            model_name='interview',
            name='rescheduled_from',
        ),
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected'), ('interview', 'Interview Scheduled'), ('withdrawn', 'Withdrawn')], default='applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='cancelled_by',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('virtual', 'Virtual (Video Call)'), ('phone', 'Phone Interview'), ('in_person', 'In-Person Interview')], default='virtual', max_length=20),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interviewer',
            field=models.CharField(default='Hiring Manager', max_length=200),
        ),
        migrations.AlterField(
            model_name='interview',
            name='location',
            field=models.TextField(blank=True, help_text='Address for in-person interviews', null=True),
        ),
        migrations.RemoveField(
            model_name='application',
            name='review_notes',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='application',
            name='reviewed_by',
        ),
    ]
