# Generated by Django 6.0.2 on 2026-03-02 10:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_application_jobs_applic_status_f83260_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='match_percentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='rule_score',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['match_percentage'], name='jobs_applic_match_p_e4711b_idx'),
        ),
    ]
