# Generated by Django 5.2.5 on 2025-12-13 11:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('Career Growth', 'Career Growth'), ('Interview Tips', 'Interview Tips'), ('Resume Writing', 'Resume Writing'), ('Salary Guide', 'Salary Guide'), ('Networking', 'Networking'), ('Work Life Balance', 'Work Life Balance')], max_length=100)),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('excerpt', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
        migrations.CreateModel(
            name='SuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Name must be at least 3 characters long'), django.core.validators.MaxLengthValidator(30, message='Name cannot exceed 30 characters')])),
                ('current_role', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3, message='Role must be at least 3 characters long'), django.core.validators.MaxLengthValidator(50, message='Role cannot exceed 50 characters')])),
                ('email', models.EmailField(max_length=254)),
                ('story_content', models.TextField(validators=[django.core.validators.MinLengthValidator(100, message='Story must be at least 100 characters long'), django.core.validators.MaxLengthValidator(2000, message='Story cannot exceed 2000 characters')])),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Published'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('consent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Success Stories',
                'ordering': ['-created_at'],
            },
        ),
    ]
